//VNJSn is copyright Patrick Martin January 2015-2018
//In this text the words Source Code refer to the original code that this work was generated from.
//In this text the word "work" refers to a specific compiled (resulting from passing the Source Code through the Closure-Compiler software) version of this software.
//This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License.
//To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/4.0/ or send a letter to Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.
//The Source Code this work was created from and any other works derived from the Source Code are not bound by this work's licence.

window.URL=window.URL||window.webkitURL||{createObjectURL:function(a){var c=new FileReader;for(c.readAsDataURL(a);1==c.readyState;);return c.result},revokeObjectURL:function(){}};window.performance=window.performance||{now:function(){return new Date|0}};
window.requestAnimationFrame=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.oRequestAnimationFrame||window.mozRequestAnimationFrame||window.Qa||function(a){var c=(window.Ha||0)+1E3/60-performance.now();setTimeout(function(){window.Ha=performance.now();a()},0>c?0:c)};function k(a){var c=a.toString().match(/(\d+\.\d{0})(\d)/);return c?parseFloat(c[1]):a.valueOf()}function u(a,c){var b=a.indexOf(c);return-1==b?[a.trim()]:[a.slice(0,b),a.slice(b+1).trim()]}window.l="/";
window.Reader=Object.create(Object,{s:{value:0,writable:!0},C:{value:[],writable:!0},init:{value:function(a){this.C=a.split("\n");this.s=0},writable:!1},hasNext:{value:function(){return this.s<this.C.length},writable:!1},next:{value:function(){return this.C[this.s++]},writable:!1}});
window.PropertiesReader=Object.create(window.Reader,{init:{value:function(a){var c=new XMLHttpRequest;c.open("GET",a,!1);c.send(null);this.C=c.responseText.split("\n");this.s=0},writable:!1},next:{value:function(){return u(this.C[this.s++],"=")},writable:!1}});
window.ScriptReader=Object.create(window.Reader,{init:{value:function(a){this.C=a.split("\n");this.s=0},writable:!1},getIndex:{value:function(){return this.s},writable:!1},setIndex:{value:function(a){this.s=a},writable:!1},peek:{value:function(){return u(this.C[this.s]," ")},writable:!1},next:{value:function(){return u(this.C[this.s++]," ")},writable:!1}});
window.VNDSSoundManager=Object.create(Object,{Y:{value:null,writable:!0},c:{value:"",writable:!0},h:{value:"",writable:!0},v:{value:[],writable:!0},b:{value:{},writable:!0},U:{value:function(a){"undefined"===typeof this.b[a]&&(this.b[a]=new Audio);var c=this,b=new XMLHttpRequest;b.onload=function(){if(4===b.readyState){if(""!=c.b[a].src)try{URL.revokeObjectURL(c.b[a].src)}catch(e){console.warn("Failed to revoke object url for sound: "+a)}if(200==b.status)c.b[a].src=URL.createObjectURL(b.response);
else if(null!=c.Y){var d=c.Y.file("sound"+window.l+a);null==d?console.error('Error: could not load sound: "'+a+'"'):(d=d.pa(),c.b[a].src=URL.createObjectURL(new Blob([d])))}}};b.open("GET",this.c+"sound"+window.l+a,!0);b.responseType="blob";b.send(null)},writable:!1},Da:{value:function(){if("undefined"!==typeof this.b[this.h])this.b[this.h].pause(),this.U(this.h),this.b[this.h].currentTime=0,this.b[this.h].play();else if(""!=this.h){this.U(this.h);try{this.b[this.h].currentTime=0}catch(a){}try{this.b[this.h].onload=
function(){this.play();this.onload=null},this.b[this.h].play()}catch(a){}}},writable:!1},playMusic:{value:function(a){"undefined"===typeof this.b[a]&&this.U(a);this.b[a].loop=!0;this.b[a].onended=function(){};this.b[a].onpause=function(){};if("undefined"!==typeof this.b[this.h]){this.b[this.h].pause();try{this.b[this.h].currentTime=0}catch(c){}}this.h=a;this.b[a].onload=function(){this.play();this.onload=null};this.b[a].play()},writable:!0},stopMusic:{value:function(){if("undefined"!==typeof this.b[this.h]){this.b[this.h].pause();
try{this.b[this.h].currentTime=0}catch(a){}this.h=""}},writable:!1},playSound:{value:function(a,c){"undefined"===typeof this.b[a]&&this.U(a);var b=this;this.b[a].loop=c;this.v.push(a);this.b[a].onended=function(){if(stop||!this.loop){this.loop=!1;b.v.splice(b.v.indexOf(a),1);try{this.currentTime=0}catch(d){}}};this.b[a].onpause=function(){this.loop=!1;b.v.splice(b.v.indexOf(a),1);try{this.currentTime=0}catch(d){}};this.b[a].stop=!1;this.b[a].onload=function(){this.play();this.onload=null};this.b[a].play()},
writable:!0},stopSounds:{value:function(){for(var a=0;a<this.v.length;a++)this.b[this.v[a]].stop=!0,this.b[this.v[a]].pause()},writable:!1},init:{value:function(a,c){this.c=a;this.ya=new Audio;this.ya.loop=!0;this.b={};var b=this,d=new XMLHttpRequest;d.onload=function(){4===d.readyState&&(200==d.status?(console.log("Loaded Sound Archive."),b.Y=new JSZip(d.response)):b.Y=new JSZip,b.Da())};d.open("GET",c,!0);d.responseType="arraybuffer";d.send(null)},writable:!1}});
window.VNDSForegroundManager=Object.create(Object,{R:{value:null,writable:!0},c:{value:"",writable:!0},$:{value:0,writable:!0},S:{value:0,writable:!0},ta:{value:Object.create(Object,{x:{value:0,writable:!0},y:{value:0,writable:!0},code:{value:null,writable:!0},data:{value:null,writable:!0}}),writable:!1},sa:{value:Object.create(Object,{path:{value:null,writable:!0},oa:{value:0,writable:!0},qa:{value:null,writable:!0},direction:{value:1,writable:!0},duration:{value:0,writable:!0},ra:{value:function(){},
writable:!0},aa:{value:0,writable:!0},handle:{value:"",writable:!0},Ga:{value:function(a){return this.path.La(this.oa*a)},writable:!1}}),writable:!0},ja:{value:{Linear:function(a){return a},InQuad:function(a){return Math.pow(a,2)},OutQuad:function(a){return a*(2-a)},InOutQuad:function(a){return.5>a?2*Math.pow(a,2):-1+(4-2*a)*a},InCubic:function(a){return Math.pow(a,3)},OutCubic:function(a){return--a*Math.pow(a,2)+1},InOutCubic:function(a){return.5>a?4*Math.pow(a,3):(a-1)*(2*a-2)*(2*a-2)+1},InQuart:function(a){return Math.pow(a,
4)},OutQuart:function(a){return 1- --a*Math.pow(a,3)},InOutQuart:function(a){return.5>a?8*Math.pow(a,4):1-8*--a*Math.pow(a,3)},InQuint:function(a){return Math.pow(a,5)},OutQuint:function(a){return 1+--a*Math.pow(a,4)},InOutQuint:function(a){return.5>a?16*Math.pow(a,5):1+16*--a*Math.pow(a,4)}},writable:!1},F:{value:[],writable:!0},Z:{value:[],writable:!0},j:{value:{},writable:!0},D:{value:{},writable:!0},Ca:{value:function(){for(var a=Object.keys(this.j),c=0;c<a.length;c++)this.fa(a[c])},writable:!1},
fa:{value:function(a){"undefined"===typeof this.j[a]&&(this.j[a]=Object.create(this.ta),this.j[a].data=new Image);var c=this,b=new XMLHttpRequest;b.onload=function(){if(4===b.readyState){if(""!=c.j[a].data.src)try{URL.revokeObjectURL(c.j[a].data.src)}catch(e){console.warn("Failed to revoke object url for sprite: "+a)}if(200==b.status)c.j[a].data.src=URL.createObjectURL(b.response);else if(null!=c.R){var d=c.R.file("foreground"+window.l+a);null==d?console.error('Error: could not load sprite: "'+a+
'"'):(d=d.pa(),c.j[a].data.src=URL.createObjectURL(new Blob([d])))}}};b.open("GET",this.c+"foreground"+window.l+a,!0);b.responseType="blob";b.send(null)},writable:!1},preloadSprite:{value:function(a){"undefined"===typeof this.j[a]&&this.fa(a)},writable:!1},showSprite:{value:function(a,c,b,d){"undefined"===typeof this.j[a]&&this.fa(a);var e=Object.create(this.j[a]);null!=d&&(this.D[d]=this.j[a],this.D[d].code=d);e.x=c/256*this.$;e.y=b/192*this.S;this.Z.push(e)},writable:!1},animateOnPath:{value:function(a,
c,b,d,e,g){var h=Object.create(this.sa);h.path=document.createElementNS("http://www.w3.org/2000/svg","path");h.path.setAttribute("d",c);h.oa=h.path.Ma();h.qa=this.ja[e]||this.ja.InOutQuad;h.direction=d;h.duration=b;h.handle=a;h.ra=g;h.aa=0;this.F.push(h)},writable:!1},animateAll:{value:function(a){for(var c=0;c<this.F.length;c++){var b=this.F[c];0==b.aa&&(b.aa=a);var d=(a-b.aa)/1E3/b.duration;1<d&&(d=1);var e=b.qa(d);reverse&&(e=1-e);e=b.Ga(e);this.D[b.handle].x=e.x/256*this.$;this.D[b.handle].y=
e.y/192*this.S;1==d&&(b.ra(),this.F.splice(this.F.indexOf(b),1),c--)}},writable:!0},setSpritePos:{value:function(a,c,b){try{this.D[a].x=c/256*this.$,this.D[a].y=b/192*this.S}catch(d){}},writable:!1},clearSprites:{value:function(){this.F=[];this.D={};this.Z=[]},writable:!1},getSpriteDelegate:{value:function(){var a=this;return{getVisibleSprites:function(){return a.Z.slice(0)}}},writable:!1},init:{value:function(a,c,b,d){this.$=a;this.S=c;this.c=b;this.j={};this.F=[];this.D={};this.Z=[];var e=this,
g=new XMLHttpRequest;g.onload=function(){4===g.readyState&&(200==g.status?(console.log("Loaded Foreground Archive."),e.R=new JSZip(g.response)):e.R=new JSZip,e.Ca())};g.open("GET",d,!0);g.responseType="arraybuffer";g.send(null)}}});
window.VNDSBackgroundManager=Object.create(Object,{P:{value:null,writable:!0},c:{value:"",writable:!0},o:{value:{},writable:!0},Ba:{value:function(){for(var a=Object.keys(this.o),c=0;c<a.length;c++)this.V(a[c])},writable:!1},V:{value:function(a){"undefined"===typeof this.o[a]&&(this.o[a]=new Image);var c=this,b=new XMLHttpRequest;b.onload=function(){if(4===b.readyState){if(""!=c.o[a].src)try{URL.revokeObjectURL(c.o[a].src)}catch(e){console.warn("Failed to revoke object url for background: "+a)}if(200==
b.status)c.o[a].src=URL.createObjectURL(b.response);else if(null!=c.P){var d=c.P.file("background"+window.l+a);null==d?console.error('Error: could not load background: "'+a+'"'):(d=d.pa(),c.o[a].src=URL.createObjectURL(new Blob([d])))}}};b.open("GET",this.c+"background"+window.l+a,!0);b.responseType="blob";b.send(null)},writable:!1},getBackground:{value:function(a){"undefined"===typeof this.o[a]&&this.V(a);return this.o[a]},writable:!1},init:{value:function(a,c){this.c=a;this.o={};var b=this,d=new XMLHttpRequest;
d.onload=function(){4===d.readyState&&(200==d.status?(console.log("Loaded Background Archive."),b.P=new JSZip(d.response)):b.P=new JSZip,b.Ba())};d.open("GET",c,!0);d.responseType="arraybuffer";d.send(null)}}});
window.VNDSGraphicsManager=Object.create(Object,{g:{value:null,writable:!0},ma:{value:null,writable:!0},J:{value:0,writable:!0},ca:{value:"monospace",writable:!0},u:{value:null,writable:!0},na:{value:0,writable:!0},f:{value:null,writable:!0},m:{value:null,writable:!0},ba:{value:1,writable:!0},a:{value:null,writable:!0},M:{value:!1,writable:!0},T:{value:!1,writable:!0},G:{value:[],writable:!0},showChoice:{value:function(a){this.G=a;this.T=!0},writable:!1},putText:{value:function(a){for(this.na=0;39<
a.length;)" "!=a[38]&&" "!=a[39]?(this.u.push(a.substring(0,39)+"-"),a="-"+a.substring(39)):(this.u.push(a.substring(0,39)),a=a.substring(39));for(this.u.push(a);128<this.u.length;)this.u.splice(0,1)},writable:!1},playMovie:{value:function(a){function c(){d.M=!1;d.m=this.ua;d.a.setPaused(0)}var b=document.createElement("video");b.ua=this.m;b.src=this.a.getRootPath()+"video"+window.l+a;this.ba=1;this.m=b;this.a.setPaused(2);this.M=!0;var d=this;b.onended=c;b.onerror=c;b.onabort=c;b.play()},writable:!1},
setBackground:{value:function(a,c){this.ba=1/(1>c?1:c);this.m=a},writable:!1},draw:{value:function(){this.f.Na=!1;this.f.Ra=!1;this.f.Pa=!1;"undefined"!==typeof this.m&&null!=this.m&&(this.m.complete&&0!=this.m.naturalWidth||this.M)&&(this.f.globalAlpha=this.ba,this.M?this.f.drawImage(this.m,(this.m.videoWidth/this.m.videoHeight*this.g.height)/2,0,this.m.videoWidth/this.m.videoHeight*this.g.height,this.g.height):this.f.drawImage(this.m,0,0,this.g.width/2,this.g.height),this.f.globalAlpha=1);if(!this.M)for(var a=this.ma.getVisibleSprites(),c=0;c<a.length;c++)this.f.drawImage(a[c].data,
a[c].x,a[c].y);this.f.fillStyle="black";this.f.fillRect(this.g.width/2,0,this.g.width,this.g.height);this.f.fillStyle="white";this.f.font=this.J+"px "+this.ca;for(c=0;15>c&&c<this.u.length;c++)this.f.fillText(this.u[this.na+this.u.length-1-c],this.g.width/2,15*this.J-this.J*c);if(this.T){a=this.G.length;var b=this.g.height/(a+5);this.f.font=b/4+"px "+this.ca;for(c=1;c<=a;c++){var d=this.f.measureText(this.G[c-1]).width,e=this.g.width/4-d/2;this.f.fillStyle="rgba(27,27,27,0.75)";this.f.fillRect(e-
5,b*c-2,d+10,b/4+4);this.f.fillStyle="white";this.f.fillText(this.G[c-1],e,b*c+3*b/16)}}},writable:!1},init:{value:function(a,c,b,d){var e=this;this.ma=d;this.a=b;this.u=[];this.g=document.createElement("canvas");this.g.width=2*a;this.g.height=c;this.g.style.height="auto";this.g.style.width=window.innerWidth+"px";this.g.style.msInterpolationMode="nearest-neighbor";this.g.addEventListener("click",function(a){if(1==e.a.getPaused())e.a.setPaused(0);else if(2==e.a.getPaused()&&e.T){var b=(a.offsetX||
a.layerX)/window.innerWidth*this.width,c=(a.offsetY||a.layerY)/window.innerWidth*this.width,d=e.G.length,f=this.height/(d+5);e.f.font=.75*e.J+"px "+e.ca;for(var g=1;g<=d;g++){var n=e.f.measureText(e.G[g-1]).width,r=this.width/4-n/2-5,t=f*g-2;n=r+n+10;var v=t+f/4+4;if(b>=r&&c>=t&&b<=n&&c<=v){e.a.setVariable("selected",g);e.T=!1;e.a.setPaused(0);break}}}a.cancelBubble=!0;return!1});this.J=c/16;document.body.appendChild(this.g);this.f=this.g.getContext("2d")}}});
window.VNDSScriptManager=Object.create(Object,{B:{value:0,writable:!0},N:{value:0,writable:!0},ia:{value:[],writable:!0},ha:{value:[],writable:!0},I:{value:"",writable:!0},a:{value:null,writable:!0},X:{value:null,writable:!0},Ea:{value:function(a){for(var c=-1;-1!=(c=a.indexOf("$",c+1));){var b=a.Oa("$",c+1);if(-1!=b)if(b=c+1)a=a.substring(0,c)+a.substring(b);else{var d=this.a.getVariable(varname)||this.a.getGlobalVariable(varname);a=a.substring(0,c)+d+a.substring(b+1)}}return a},writable:!1},va:{value:function(a){var c=
a.trim();if("#"==c[0])return"#";"fi"==c&&this.B--;for(c=0;"\t"==a[c];c++);c!=this.B&&(this.a.setPaused(3),console.error("ERROR: Script Invalid ("+this.I+":"+(this.i.getIndex()-1)+") - Expected depth is: "+this.B+" Found: "+c));return a.substring(c)},writable:!1},wa:{value:function(a){a=a.trim().split(" ");if(3!=a.length)return this.a.setPaused(3),console.error("ERROR: Script Invalid ("+this.I+":"+(this.i.getIndex()-1)+") - Invalid if statement with "+a.length+" parts."),!1;var c=parseInt(a[0]),b=
parseInt(a[2]),d=a[1].trim();isNaN(c)&&(c=this.a.getVariable(a[0])||this.a.getGlobalVariable(a[0])||0);isNaN(b)&&(b=this.a.getVariable(a[2].trim())||this.a.getGlobalVariable(a[2].trim())||0);if("=="==d)return c==b;if("!="==d)return c!=b;if(">="==d)return c>=b;if("<="==d)return c<=b;if(">"==d)return c>b;if("<"==d)return c<b;this.a.setPaused(3);console.error("ERROR: Script Invalid ("+this.I+":"+(this.i.getIndex()-1)+') - Unknown conditional operation "'+d+'".');return!1},writable:!1},za:{value:function(a){var c=
1;"~"==a[0]?this.a.putText(""):"!"==a[0]?this.N||this.a.setPaused(1):("@"==a[0]&&(a=a.substring(1),c=0),this.a.putText(a),this.N||this.a.setPaused(c))},writable:!1},da:{value:function(a){this.B=0;this.i.setIndex(0);for(var c=!1;this.i.hasNext()&&!c;){var b=this.i.next();"label"==b[0].trim()?b[1]==a&&(c=!0):"if"==b[0].trim()?this.B++:"fi"==b[0].trim()&&this.B--}this.i.hasNext()||console.error('Error: could not find label "'+a+'"')},writable:!1},setSkipping:{value:function(a){this.N=a},writable:!1},
parse:{value:function(){if(this.i.hasNext()){var a=this.i.next();a[0]=this.va(a[0]);a[1]&&(a[1]=this.Ea(a[1]));var c=this;switch(a[0].trim()){case "push":this.ia.push(parseInt(a[1])||a[1]);break;case "pop":this.a.setVariable(a[1],this.ia.pop());break;case "gosub":this.ha.push(this.i.getIndex());this.da(a[1]);break;case "return":this.i.setIndex(this.ha.pop());break;case "bgload":a=a[1].split(" ");this.a.loadBackground(a[0],a[1]||0);break;case "playmovie":this.a.playMovie(a[1]);break;case "text":this.za(a[1]);
break;case "delay":this.N||(this.a.setPaused(2),window.setTimeout(function(){c.a.setPaused(0)},1E3/60*parseInt(a[1])));break;case "choice":this.a.setPaused(2);this.a.showChoice(a[1].split("|"));break;case "if":if(this.wa(a[1]))this.B++;else for(a=0;this.i.hasNext()&&-1!=a;){var b=this.i.next()[0];"if"==b.trim()?a++:"fi"==b.trim()&&a--}break;case "setimg":a=a[1].split(" ");this.a.showSprite(a[0],parseInt(a[1])||0,parseInt(a[2])||0,a[3]||null);break;case "setpos":a=a[1].split(" ");this.a.setSpritePos(a[0],
parseInt(a[1])||0,parseInt(a[2])||0);break;case "animate":var d=u(a[1]," ");a=d[0];d=u(d[1]," ");var e=parseInt(d[0])||parseBoolean(d[0]);d=u(d[1]," ");b=1E3/60*parseInt(d[0]);d=u(d[1]," ");var g="reverse"!=d[0]?1:-1;d=u(d[1]," ");var h=d[0];d=d[1];e&&(this.L=2);this.a.animateOnPath(a,d,b,g,h,function(){e&&(c.L=0)});break;case "sound":a=a[1].split(" ");b=!1;"undefined"!==typeof a[1]&&(b=parseInt(a[1]),b=isNaN(b)?"true"==a[1]:0<b);"~"==a[0]?this.a.stopSounds():this.a.playSound(a[0],b);break;case "music":"~"==
a[1]?this.a.stopMusic():this.a.playMusic(a[1]);break;case "setvar":b=a[1].split(" ");"+"==b[1]?this.a.setVariable(b[0],this.a.getVariable(b[0])+parseInt(b[2])):"-"==b[1]?this.a.setVariable(b[0],this.a.getVariable(b[0])-parseInt(b[2])):"="==b[1]?this.a.setVariable(b[0],parseInt(b[2])):"*"==b[1]?this.a.setVariable(b[0],this.a.getVariable(b[0])*parseInt(b[2])):"/"==b[1]&&this.a.setVariable(b[0],this.a.getVariable(b[0])/parseInt(b[2]));break;case "gsetvar":a=a[1].split(" ");"+"==a[1]?this.a.setGlobalVariable(b[0],
this.a.getGlobalVariable(b[0])+parseInt(b[2])):"-"==a[1]?this.a.setGlobalVariable(b[0],this.a.getGlobalVariable(b[0])-parseInt(b[2])):"="==a[1]?this.a.setGlobalVariable(b[0],parseInt(b[2])):"*"==a[1]?this.a.setGlobalVariable(b[0],this.a.getGlobalVariable(b[0])*parseInt(b[2])):"/"==a[1]&&this.a.setGlobalVariable(b[0],this.a.getGlobalVariable(b[0])/parseInt(b[2]));break;case "random":a=a[1].split(" ");this.a.setVariable(a[0],k(parseInt(a[1])+Math.floor(Math.random()*(parseInt(a[2])-parseInt(a[1])+1))));
break;case "goto":this.da(a[1]);break;case "cleartext":break;case "endscript":this.K("main.scr");break;case "jump":this.N||this.a.setPaused(1);b=a[1].split(" ");2==b.length?(this.K(b[0]),this.da(b[1])):this.K(a[1]);break;case "#":case "label":case "fi":case "":break;default:console.warn('Warning: unknown script command "'+a[0]+'"')}}else this.K("main.scr")},writable:!1},K:{value:function(a){this.B=0;var c=new XMLHttpRequest;c.open("GET",this.c+"script"+window.l+a,!1);c.send(null);200==c.status?(this.i.init(c.responseText.replace(/    /g,
"\t").replace(/\r/g,"")),this.I=a):this.X&&(c=this.X.file("script"+window.l+a),null!=c&&(this.i.init(c.Ka().replace(/    /g,"\t").replace(/\r/g,"")),this.I=a));for(;this.i.hasNext();)a=this.i.next(),"setimg"==a[0].trim()?this.a.preloadSprite(a[1].split(" ")[0]):"bgload"==a[0].trim()&&this.a.preloadBackground(a[1]);this.i.setIndex(0)},writable:!1},init:{value:function(a,c){this.a=a;this.c=c;this.i=Object.create(window.ScriptReader);var b=this,d=new XMLHttpRequest;d.onload=function(){4===d.readyState&&
(200==d.status?(console.log("Loaded Script Archive."),b.X=new JSZip(d.response)):b.X=new JSZip,b.K("main.scr"))};d.open("GET",this.c+"script.zip",!0);d.responseType="arraybuffer";d.send(null)},writable:!1}});
window.VNDSPrototype=Object.create(Object,{L:{value:0,writable:!0},c:{value:null,writable:!0},ga:{value:{},writable:!0},ea:{value:{},writable:!0},W:{value:null,writable:!0},H:{value:null,writable:!0},O:{value:null,writable:!0},A:{value:null,writable:!0},ka:{value:0,writable:!0},xa:{value:function(a,c,b,d){c=c.createImageData(b,d);a=window.localStorage.getItem("slot["+a+"][icon]").split(",");for(b=0;b<c.data.length;b++)c.data[b]=parseInt(a[b]);return c},writable:!1},Fa:{value:function(a,c){for(var b=
"",d=0;d<c.data.length;d++)b+=c.data[d]+",";window.localStorage.setItem("slot["+a+"][icon]",b)},writable:!1},Aa:{value:function(a){this.O.getBackground(a)},writable:!1},V:{value:function(a,c){var b=this.O.getBackground(a);this.A.setBackground(b,c);this.w.clearSprites()},writable:!1},la:{value:function(){0==this.L&&this.W.parse();var a=performance.now();a-this.ka>=1E3/60&&(this.w.animateAll(a),this.A.draw(),this.ka=performance.now());var c=this;window.requestAnimationFrame(function(){c.la()})},writable:!1},
init:{value:function(a,c){this.c="vnds"+window.l+"novels"+window.l+a+window.l;this.ga={};this.ea={};var b=Object.create(window.PropertiesReader),d=Object.create(window.PropertiesReader);this.W=Object.create(window.VNDSScriptManager);this.A=Object.create(window.VNDSGraphicsManager);this.H=Object.create(window.VNDSSoundManager);this.O=Object.create(window.VNDSBackgroundManager);this.w=Object.create(window.VNDSForegroundManager);b.init(this.c+"info.txt");d.init(this.c+"img.ini");for(var e,g;b.hasNext();){var h=
b.next();switch(h[0]){case "title":e=h[1];break;case "opening":g=h[1]}}"undefined"===typeof c?document.title=e||document.title:c(e);for(var p,q;d.hasNext();)switch(h=d.next(),h[0]){case "width":p=parseInt(h[1]);break;case "height":q=parseInt(h[1])}var f=this,m={setPaused:function(a){f.L=a},getPaused:function(){return f.L},getVariable:function(a){return f.ga[a]},setVariable:function(a,b){f.ga[a]=b},getGlobalVariable:function(a){return f.ea[a]},setGlobalVariable:function(a,b){f.ea[a]=b},playMusic:function(a){f.H.playMusic(a)},
stopMusic:function(){f.H.stopMusic()},playSound:function(a,b){f.H.playSound(a,b)},stopSounds:function(){f.H.stopSounds()},preloadSprite:function(a){f.w.preloadSprite(a)},showSprite:function(a,b,c,d){f.w.showSprite(a,b,c,d)},setSpritePos:function(a,b,c){f.w.setSpritePos(a,b,c)},animateOnPath:function(a,b,c,d,e,g){f.w.animateOnPath(a,b,c,d,e,g)},showChoice:function(a){f.A.showChoice(a)},playMovie:function(a){f.A.playMovie(a)},preloadBackground:function(a){f.Aa(a)},loadBackground:function(a,b){f.V(a,
b)},putText:function(a){f.A.putText(a)},setSkipping:function(a){f.W.setSkipping(a)},save:function(a){f.Ja(a)},load:function(a){f.Ia(a)},getSaveIcon:function(a,b,c,d){return f.xa(a,b,c,d)},setSaveIcon:function(a,b){return f.Fa(a,b)},getRootPath:function(){return f.c}};window.addEventListener("keydown",function(a){17==a.keyCode&&(1==m.getPaused()&&m.setPaused(0),m.setSkipping(1))},!1);window.addEventListener("keyup",function(a){17==a.keyCode&&m.setSkipping(0)},!1);this.W.init(m,this.c,this.c+"script.zip");
this.H.init(this.c,this.c+"sound.zip");this.O.init(this.c,this.c+"background.zip");this.w.init(p,q,this.c,this.c+"foreground.zip");this.A.init(p,q,m,this.w.getSpriteDelegate());"undefined"!==typeof g&&this.A.playMovie(g);window.requestAnimationFrame(function(){f.la()})},writable:!1}});